# Generated by Django 4.1.6 on 2023-02-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cmsslider_cms_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_css',
            field=models.CharField(default='-', max_length=258, null=True, verbose_name='CSS класс'),
        ),
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_text',
            field=models.CharField(max_length=258, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_title',
            field=models.CharField(max_length=258, verbose_name='Заголовок'),
        ),
    ]
