# Generated by Django 4.1.6 on 2023-02-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telesettings',
            options={'verbose_name': 'Настройку', 'verbose_name_plural': 'Настройки'},
        ),
    ]
